### ISSUE TITLE
Problem validating B2C invoices

### ISSUE THREAD

**Issue by tengvig** [difi/vefa-validator-conf#174] opened 2016-09-27 11:52 UTC
My existing B2C invoices fails validation with:

```
<section title="Sjekk mot norske nasjonale regler" flag="error" runtime="9ms" configuration="ehf-t10-base-2.0" build="e6bc17f42b843fa980934c0db69833a781dc2e35">
        <assertion identifier="UNKNOWN" flag="error">
            <text>PartyLegalEntity for AccountingCustomerParty MUST be provided according to EHF.</text>
            <location>/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]/*:AccountingCustomerParty[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]/*:Party[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]</location>
            <test>$isB2C or (cac:PartyLegalEntity/cbc:CompanyID != '')</test>
        </assertion>
        <assertion identifier="UNKNOWN" flag="error">
            <text>Registration name for AccountingCustomerParty MUST be provided according to EHF.</text>
            <location>/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]/*:AccountingCustomerParty[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]/*:Party[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]</location>
            <test>$isB2C or (cac:PartyLegalEntity/cbc:RegistrationName != '')</test>
        </assertion>

```
Is the test **$isB2C or (cac:PartyLegalEntity/cbc:RegistrationName != '')** correct?
Will this test fail for all B2C invoices?

**Comment by klakegg** [comment] 2016-09-27 13:16
Please provide example data.

**Comment by tengvig** [comment] 2016-09-28 08:40
Example data provided.
This file passes the online validator at https://test-vefa.difi.no/validator
It does not pass the test when using the java vefa validator version 2.0.2.

It's a bit odd that the online validator uses the same build of  ehf-t10-base-2.0 as the java validator:   d28b5c4cc8458ca59cedd3bc89f247487552e3ae

The online validator gives warnings with correct identifiers, e.g. NONAT-T10-R003 The actual delivery date SHOULD be provided in the invoice according to "FOR 2004-12-01 nr 1558 - § 5-1-1. Point 4 and § 5-1-4", see also “NOU 2002:20, point 9.4.1.4”"

but the java validator issues warnings with UNKNOWN identifiers, e.g. 
```
       <assertion identifier="UNKNOWN" flag="warning">
            <text>The actual delivery date SHOULD be provided in the invoice according to "FOR 2004-12-01 nr 1558 - § 5-1-1. Point 4 and § 5-1-4", see also “NOU 2002:20, point 9.4.1.4”"</text>
            <location>/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]</location>
            <test>//cac:Delivery/cbc:ActualDeliveryDate</test>

```
This only applies to ehf-t10-base-2.0. Validation warnings against ehf-t10-core-2.0 gives correct identifiers.
[b2c-feiler.txt](https://github.com/difi/vefa-validator-conf/files/497493/b2c-feiler.txt)

**Comment by klakegg** [comment] 2016-09-28 19:56
Is this about the identifier attribute, or something else? I'm trying to grasp exactly what is the reported problem.

**Comment by klakegg** [comment] 2016-09-28 19:58
By the way, the Difi services use a newer unversioned edition of the validator code, this is important to remember when I look for the error.

**Comment by tengvig** [comment] 2016-09-29 06:51
The UNKNOWN identifier attribute is just an observation, the problem is that B2C invoices that previously  used to pass validation now fails with an error:

```
<section title="Sjekk mot norske nasjonale regler" flag="error" runtime="9ms" configuration="ehf-t10-base-2.0" build="e6bc17f42b843fa980934c0db69833a781dc2e35">
        <assertion identifier="UNKNOWN" flag="error">
            <text>PartyLegalEntity for AccountingCustomerParty MUST be provided according to EHF.</text>
            <location>/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]/*:AccountingCustomerParty[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]/*:Party[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]</location>
            <test>$isB2C or (cac:PartyLegalEntity/cbc:CompanyID != '')</test>
        </assertion>
        <assertion identifier="UNKNOWN" flag="error">
            <text>Registration name for AccountingCustomerParty MUST be provided according to EHF.</text>
            <location>/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]/*:AccountingCustomerParty[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]/*:Party[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]</location>
            <test>$isB2C or (cac:PartyLegalEntity/cbc:RegistrationName != '')</test>
        </assertion>

```

I've just run the tests again. Did you change the rulsesets yesterday, because now the tests pass :)
I.e. this issue can be closed.

**Comment by klakegg** [comment] 2016-09-29 10:27
I didn't change anything related to these rules. The identifier will be fixed next week.

**Comment by tengvig** [comment] 2016-09-30 08:03
I've created a new testcase. If I only validate the B2C invoice, it will pass the test. If I validate the B2B invoice first, and then the B2C invoice - using the same validator - the B2C invoice will fail. This only occurs when the validator is set up to use RepositorySource.forTest

[b2b-faktura.xml.txt](https://github.com/difi/vefa-validator-conf/files/502373/b2b-faktura.xml.txt)
[b2c-faktura.xml.txt](https://github.com/difi/vefa-validator-conf/files/502374/b2c-faktura.xml.txt)
[ValidatorTest.java.txt](https://github.com/difi/vefa-validator-conf/files/502375/ValidatorTest.java.txt)

**Comment by klakegg** [comment] 2016-09-30 16:54
I'm able to reproduce this with version 2.0.2 of the validator. The problem seems to be related to the Saxon library. When I upgrade Saxon to version 9.7.0-6 disappears this defect.

Could you please verify?

**Comment by tengvig** [comment] 2016-10-03 08:12
After I upgraded Saxon the problem disappears, and the invoice validates correctly.

**Closed** 2016-10-15 11:51 UTC
Labels: Invoice, Validator
